// Rich Mock Data baseline for offline/local sandbox mode matching firebase schemas in docs/firebase-implementation/SKILL.md

export interface MockDataStore {
  users: any[];
  departments: any[];
  programs: any[];
  sections: any[];
  teachers: any[];
  students: any[];
  courses: any[];
  rooms: any[];
  schedules: any[];
  auditLogs: any[];
  terms?: any[];
  courseOfferings?: any[];
  institutionSettings?: any;
}

export const mockData: MockDataStore = {
  users: [
    {
      id: "7utO6Dqf8YOWeF4ZAeWVXbs2NyV2",
      uid: "7utO6Dqf8YOWeF4ZAeWVXbs2NyV2",
      email: "wwen485@gmail.com",
      displayName: "John Doe (Super Admin)",
      role: "admin",
      status: "active",
      departmentId: "cs-dept",
      createdAt: new Date("2026-01-01"),
      updatedAt: new Date("2026-05-18"),
    },
    {
      id: "user-001",
      uid: "user-001",
      email: "john.smith@university.edu",
      displayName: "Dr. John Smith",
      role: "teacher",
      status: "active",
      departmentId: "cs-dept",
      createdAt: new Date("2026-01-10"),
      updatedAt: new Date("2026-05-18"),
    },
    {
      id: "user-002",
      uid: "user-002",
      email: "sarah.johnson@university.edu",
      displayName: "Prof. Sarah Johnson",
      role: "teacher",
      status: "active",
      departmentId: "math-dept",
      createdAt: new Date("2026-01-12"),
      updatedAt: new Date("2026-05-18"),
    },
    {
      id: "user-003",
      uid: "user-003",
      email: "alice.brown@university.edu",
      displayName: "Alice Brown",
      role: "student",
      status: "active",
      departmentId: "cs-dept",
      createdAt: new Date("2026-02-01"),
      updatedAt: new Date("2026-05-18"),
    },
  ],
  departments: [
    {
      id: "cs-dept",
      code: "CS",
      name: "Computer Science Department",
      chairUid: "user-001",
      createdAt: new Date("2026-01-01"),
    },
    {
      id: "math-dept",
      code: "MATH",
      name: "Mathematics Department",
      chairUid: "user-002",
      createdAt: new Date("2026-01-01"),
    },
  ],
  programs: [
    {
      id: "bscs",
      departmentId: "cs-dept",
      code: "BSCS",
      name: "Bachelor of Science in Computer Science",
      createdAt: new Date("2026-01-02"),
    },
    {
      id: "bsmath",
      departmentId: "math-dept",
      code: "BSMATH",
      name: "Bachelor of Science in Mathematics",
      createdAt: new Date("2026-01-02"),
    },
  ],
  sections: [
    {
      id: "section-bscs-3a",
      programId: "bscs",
      name: "BSCS-3A",
      yearLevel: 3,
      studentCount: 32,
      advisorUid: "user-001",
      targets: { minUnits: 12, maxUnits: 18 },
    },
    {
      id: "section-bsmath-2b",
      programId: "bsmath",
      name: "BSMATH-2B",
      yearLevel: 2,
      studentCount: 25,
      advisorUid: "user-002",
      targets: { minUnits: 12, maxUnits: 18 },
    },
  ],
  teachers: [
    {
      id: "teacher-001",
      uid: "user-001",
      employeeNo: "EMP-2026-102",
      fullName: "Dr. John Smith",
      departmentId: "cs-dept",
      designation: "Associate Professor",
      employmentType: "Full-time",
      specialization: "Artificial Intelligence, Algorithms",
      major: "Computer Science",
      certifications: ["AWS Certified ML Specialist", "Google Cloud Professional ML Engineer", "Oracle Java SE Certified Professional"],
      skills: ["Machine Learning", "Python", "Deep Learning", "Algorithms Design", "React", "TypeScript", "SQL"],
      teachingExperience: "12 Years",
      eligibleSubjects: ["CS-101", "CS-202"],
      officeLocation: "Tech Hall, Room 402",
      targetUnits: 18,
    },
    {
      id: "teacher-002",
      uid: "user-002",
      employeeNo: "EMP-2026-105",
      fullName: "Prof. Sarah Johnson",
      departmentId: "math-dept",
      designation: "Professor",
      employmentType: "Full-time",
      specialization: "Applied Calculus, Linear Algebra",
      major: "Applied Mathematics",
      certifications: ["Certified Financial Risk Analyst (CFRA)", "Data Science Professional Certificate"],
      skills: ["Calculus", "Linear Algebra", "Statistical Modeling", "Matlab", "Python", "R"],
      teachingExperience: "15 Years",
      eligibleSubjects: ["MATH-101"],
      officeLocation: "Science Building, Room 204",
      targetUnits: 15,
    },
  ],
  students: [
    {
      id: "student-001",
      uid: "user-003",
      studentNo: "STUD-2026-8801",
      fullName: "Alice Brown",
      programId: "bscs",
      sectionId: "section-bscs-3a",
      yearLevel: 3,
      major: "Data Science",
      gpa: 3.82,
    },
  ],
  courses: [
    {
      id: "CS-101",
      code: "CS-101",
      name: "Introduction to Computer Science",
      description: "Basic programming, logic, and concepts of computing.",
      units: 3,
      lectureHours: 2,
      labHours: 3,
      category: "major",
      departmentId: "cs-dept",
      isActive: true,
    },
    {
      id: "MATH-101",
      code: "MATH-101",
      name: "Calculus I",
      description: "Limits, derivatives, integrals, and mathematical modeling.",
      units: 4,
      lectureHours: 4,
      labHours: 0,
      category: "major",
      departmentId: "math-dept",
      isActive: true,
    },
    {
      id: "CS-202",
      code: "CS-202",
      name: "Data Structures & Algorithms",
      description: "Arrays, lists, trees, graphs, hashing, and complexity.",
      units: 3,
      lectureHours: 2,
      labHours: 3,
      category: "major",
      departmentId: "cs-dept",
      isActive: true,
    },
  ],
  rooms: [
    {
      id: "room-001",
      name: "Lab 101",
      building: "Science Building",
      floor: 1,
      capacity: 30,
      type: "laboratory",
      status: "available",
      features: ["Computers", "Projector", "Whiteboard"],
    },
    {
      id: "room-002",
      name: "Lecture Hall A",
      building: "Main Building",
      floor: 2,
      capacity: 100,
      type: "lecture",
      status: "available",
      features: ["Sound System", "High-capacity", "AC"],
    },
  ],
  schedules: [
    {
      id: "schedule-001",
      courseId: "CS-101",
      teacherId: "user-001",
      roomId: "room-001",
      dayOfWeek: "Monday",
      startTime: "09:00",
      endTime: "10:30",
      semester: "Spring 2026",
    },
    {
      id: "schedule-002",
      courseId: "MATH-101",
      teacherId: "user-002",
      roomId: "room-002",
      dayOfWeek: "Wednesday",
      startTime: "10:00",
      endTime: "11:30",
      semester: "Spring 2026",
    },
    {
      id: "schedule-003",
      courseId: "CS-202",
      teacherId: "user-001",
      roomId: "room-001",
      dayOfWeek: "Thursday",
      startTime: "14:00",
      endTime: "15:30",
      semester: "Spring 2026",
    },
  ],
  auditLogs: [
    {
      id: "log-001",
      actorUid: "7utO6Dqf8YOWeF4ZAeWVXbs2NyV2",
      action: "OPTIMIZATION_STARTED",
      resourceType: "timetable",
      resourceId: "term-2026-s1",
      metadata: { term: "Spring 2026" },
      createdAt: new Date("2026-05-18T09:12:00Z"),
    },
    {
      id: "log-002",
      actorUid: "7utO6Dqf8YOWeF4ZAeWVXbs2NyV2",
      action: "SCHEDULE_PUBLISHED",
      resourceType: "timetable",
      resourceId: "term-2026-s1",
      metadata: { versionId: "v3.1" },
      createdAt: new Date("2026-05-18T10:05:00Z"),
    },
  ],
  terms: [
    {
      id: "term-2026-1st",
      academicYear: "2025-2026",
      semester: "1st",
      startDate: new Date("2026-06-01"),
      endDate: new Date("2026-10-30"),
      isCurrent: true,
      createdAt: new Date("2026-01-15"),
    },
    {
      id: "term-2026-2nd",
      academicYear: "2025-2026",
      semester: "2nd",
      startDate: new Date("2026-11-01"),
      endDate: new Date("2027-03-31"),
      isCurrent: false,
      createdAt: new Date("2026-01-15"),
    },
    {
      id: "term-2026-summer",
      academicYear: "2025-2026",
      semester: "Summer",
      startDate: new Date("2027-04-15"),
      endDate: new Date("2027-05-31"),
      isCurrent: false,
      createdAt: new Date("2026-01-15"),
    },
  ],
};
